# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: voice-assistant-alice

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en


pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    constrain_similarities: True
    epochs: 100
  - name: EntitySynonymMapper
  - name: FallbackClassifier #  intent nlu_fallback will be predicted if all other intent predictions fall below  threshold
    threshold: 0.6
  # - name: RegexEntityExtractor
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions: ["time","number"]
    locale: en_US
    timezone: Europe/Luxembourg
    timeout: 3.0

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
    check_for_contradictions: True # make sure that slots & active loops set by actions are defined consistently for all rules
  - name: MemoizationPolicy
  - name: TEDPolicy
    constrain_similarities: True
    max_history: 5
    epochs: 100
 